# FCNT Tracker Config

# Dataset
dataset:
  seq_path: "data/training023"
  # x y, w, h
  initial_bbox: [992.0, 678.0, 188.0, 140.0]

pf_param:
  affsig: [10, 10, 0.004, 0.00, 0.00, 0]
  p_sz: 64
  p_num: 700
  mv_thr: 0.1
  up_thr: 0.35
  roi_scale: 2

tracker:
  in_channels: 384
  roi_size: 368
  # Number of iterations for initial saliency map selection and tuning
  max_iter_select: 100
  # Number of iterations for training the saliency networks after selection
  max_iter: 50

  selCNN:
    in_channels: 512
    out_channels: 1
    kernel_size: 3
    padding: 1
    dropout_rate: 0.3
    bias_init: 0.0
    weight_std: 1e-7
    learning_rate: 1e-4
    weight_decay: 0.005
    top_k_features: 384
    input_size: [46, 46]
    momentum: 0.9
  gnet:
    weight_std: 1e-7
    learning_rate: 1e-3
    momentum: 0.9

  snet:
    weight_std: 1e-7
    learning_rate: 1e-3
    momentum: 0.9
